/// <reference types="expo/types" />
/// <reference types="nativewind/types" />

// NOTE: This file should be auto-generated by Expo CLI, but we are creating it manually
// to ensure TS doesn't complain before the first run.
