/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login-history`; params?: Router.UnknownInputParams; } | { pathname: `/report`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cases` | `/cases`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/evidence_tab` | `/evidence_tab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/evidence/intake`; params?: Router.UnknownInputParams; } | { pathname: `/evidence/log`; params?: Router.UnknownInputParams; } | { pathname: `/evidence/transfer`; params?: Router.UnknownInputParams; } | { pathname: `/cases/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/evidence/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login-history`; params?: Router.UnknownOutputParams; } | { pathname: `/report`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cases` | `/cases`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/evidence_tab` | `/evidence_tab`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/evidence/intake`; params?: Router.UnknownOutputParams; } | { pathname: `/evidence/log`; params?: Router.UnknownOutputParams; } | { pathname: `/evidence/transfer`; params?: Router.UnknownOutputParams; } | { pathname: `/cases/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/evidence/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login-history${`?${string}` | `#${string}` | ''}` | `/report${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cases${`?${string}` | `#${string}` | ''}` | `/cases${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/evidence_tab${`?${string}` | `#${string}` | ''}` | `/evidence_tab${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/evidence/intake${`?${string}` | `#${string}` | ''}` | `/evidence/log${`?${string}` | `#${string}` | ''}` | `/evidence/transfer${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login-history`; params?: Router.UnknownInputParams; } | { pathname: `/report`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cases` | `/cases`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/evidence_tab` | `/evidence_tab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/evidence/intake`; params?: Router.UnknownInputParams; } | { pathname: `/evidence/log`; params?: Router.UnknownInputParams; } | { pathname: `/evidence/transfer`; params?: Router.UnknownInputParams; } | `/cases/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/evidence/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/cases/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/evidence/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
